name: taskflow

volumes:
  tasks_data:
  flow_data:
  minio:

networks:
  web:
    external: true
  internal_network:
    driver: bridge

services:

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    env_file:
      - ./tasks/.env.tasks
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    networks:
      - web
      - internal_network

  redis:
    container_name: redis
    image: redis:7
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - internal_network

  tasks_db:
    container_name: tasks_database
    image: postgres:14.0
    env_file:
      - ./tasks/.env.tasks
    volumes:
      - tasks_data:/var/lib/postgresql/data
    networks:
      - internal_network

  flow_db:
    container_name: flow_database
    image: postgres:14.0
    env_file:
      - ./flow/.env.flow
    volumes:
      - flow_data:/var/lib/postgresql/data
    networks:
      - internal_network

  celeryworker:
    container_name: celeryworker
    build:
      context: .
      dockerfile: tasks/Dockerfile
    env_file:
      - ./tasks/.env.tasks
    environment:
      - POSTGRES_HOST=tasks_db
      - REDIS_HOST=redis
    depends_on:
      - redis
      - tasks_db
    command: celery -A beat.celery.celery_app worker -l INFO
    networks:
      - internal_network

  celerybeat:
    container_name: celerybeat
    build:
      context: .
      dockerfile: tasks/Dockerfile
    env_file:
      - ./tasks/.env.tasks
    environment:
      - POSTGRES_HOST=tasks_db
      - REDIS_HOST=redis
    depends_on:
      - redis
      - tasks_db
    command: celery -A beat.celery.celery_app beat -l INFO
    networks:
      - internal_network

  tasks_backend:
    container_name: tasks_backend
    build:
      context: .
      dockerfile: tasks/Dockerfile
    env_file:
      - ./tasks/.env.tasks
    environment:
      - POSTGRES_HOST=tasks_db
      - REDIS_HOST=redis
      - MINIO_URL=minio:9000
    depends_on:
      - tasks_db
      - redis
      - celeryworker
      - celerybeat
    networks:
      - internal_network

  flow_backend:
    container_name: flow_backend
    build:
      context: .
      dockerfile: flow/Dockerfile
    env_file:
      - ./flow/.env.flow
    environment:
      - POSTGRES_HOST=flow_db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
    depends_on:
      - flow_db
    networks:
      - internal_network

  gateway:
    container_name: proxy
    build: ./gateway
    depends_on:
      - tasks_backend
      - flow_backend
    ports:
      - "80:80"
    networks:
      - web
      - internal_network
