name: taskflow

volumes:
  tasks_data:
  flow_data:
  minio:
  redis_data:

networks:
  internal_network:
    driver: bridge

services:

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    env_file:
      - ./tasks/.env.tasks
    volumes:
      - minio:/data
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - internal_network

  redis:
    container_name: redis
    image: redis:7
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - internal_network

  tasks_db:
    container_name: tasks_database
    image: postgres:14.0
    env_file:
      - ./tasks/.env.tasks
    volumes:
      - tasks_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal_network

  flow_db:
    container_name: flow_database
    image: postgres:14.0
    env_file:
      - ./flow/.env.flow
    volumes:
      - flow_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - internal_network

  celeryworker:
    container_name: celeryworker
    build:
      context: .
      dockerfile: tasks/Dockerfile
    env_file:
      - ./tasks/.env.tasks
    environment:
      - POSTGRES_HOST=tasks_db
      - REDIS_HOST=redis
    depends_on:
      - redis
      - tasks_db
    command: celery -A beat.celery.celery_app worker -l INFO
    networks:
      - internal_network

  celerybeat:
    container_name: celerybeat
    build:
      context: .
      dockerfile: tasks/Dockerfile
    env_file:
      - ./tasks/.env.tasks
    environment:
      - POSTGRES_HOST=tasks_db
      - REDIS_HOST=redis
    depends_on:
      - redis
      - tasks_db
    command: celery -A beat.celery.celery_app beat -l INFO
    networks:
      - internal_network
